name: Deploy on Production
on: [push]
jobs:
  Deploy_to_production_server:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Deploy to production server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.PROD_HOST }}
        username: ${{ secrets.PROD_USERNAME }}
        key: ${{ secrets.PROD_KEY }}
        port: ${{ secrets.PROD_PORT }}
        command_timeout: 30m
        script: | 
          cd ${{secrets.PROD_PROJECT_DIR}}
          export GIT_TRACE_PACKET=1
          export GIT_TRACE=1
          export GIT_CURL_VERBOSE=1
          git config pull.rebase true
          git pull origin main
          npm i
          npm run build
          composer update
          php artisan event:cache 
          php artisan route:cache
          php artisan view:cache
          php artisan optimize:clear
          php artisan migrate
          php artisan storage:link
          

  
