name: Push to server
on: [push]
jobs:
    SSH_and_Build:
      runs-on: ubuntu-latest
      timeout-minutes: 5
      steps:
      - name: SSH & Build
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          command_timeout: 30m
          script: | 
            cd ${{secrets.PROJECT_DIR}}
            git fetch && git pull
            npm i
            npm run build
            composer install
            php artisan config:cache
            php artisan event:cache 
            php artisan route:cache
            php artisan view:cache