name: remote ssh command
on: [push]
jobs:

  build:
    name: Prepare for ssh
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create files and folders
        run: |
            cd ~ && mkdir .ssh
            touch ~/.ssh/deploy_key_rsa
            touch ~/.ssh/config
      - name: Print Secrets
        run: |
            echo $DEPLOY_KEY >> ~/.ssh/deploy_key_rsa
            cat ~/.ssh/deploy_key_rsa
            echo -e $CONFIG >> ~/.ssh/config
            cat ~/.ssh/deploy_key_rsa
        shell: bash
        env:
          DEPLOY_KEY : ${{secrets.DEPLOY_KEY_RSA}}
          CONFIG: ${{secrets.CONFIG}}
      - name: Build Deploy Key Artifact
        uses: actions/upload-artifact@v2
        with:
          name: DEPLOY_KEY
          path: ~/.ssh/deploy_key_rsa

      - name: Build Config File Artifact
        uses: actions/upload-artifact@v2
        with:
          name: CONFIG
          path: ~/.ssh/config
      
      - name: Set Permissions
        run: |
            chmod 600 ~/.ssh/deploy_key_rsa
            chmod 600 ~/.ssh/config
      - name: SSH into Wisedev
        run: |
            ssh wisedev
            whoami
